@host_name=localhost
@port=8080
@host={{host_name}}:{{port}}
@client_id=m2m.client
@scope=productapi.read
@client_secret=511536EF-F270-4058-80CA-1C89C192F69A
@grant_type=client_credentials
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkI5REMxOTQ3RUI5QjA4QTUwOTY1MkY2Q0U5QTI5MTEzIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MDgwIiwibmJmIjoxNjk5MDI3MTczLCJpYXQiOjE2OTkwMjcxNzMsImV4cCI6MTY5OTAzMDc3MywiYXVkIjpbInByb2R1Y3RhcGkiLCJodHRwczovL2xvY2FsaG9zdDo4MDgwL3Jlc291cmNlcyJdLCJzY29wZSI6WyJwcm9kdWN0YXBpLnJlYWQiXSwiY2xpZW50X2lkIjoibTJtLmNsaWVudCIsImp0aSI6Ijk5OEZBNEFCMTRCRDQ0RjFBQjFCQUVDRkE1NjQ2RDg1In0.hTLCA4r2HXwPjq6IlWIJYST5MZwhKiysvfIUNCQ3bRr47SJdW2rDxjeBtnGQBtlgdJ9vZ-4gqsiPVCRir3fh_WC8FViYEuwW4fhBBiqx9uj6LJyIXrCsprC_YJvcaZ8xr3elM76IbsdMS4gD2FucGIvQf1AVHJpTpD5ggeZIDfLr1N0uKeXij1J8zowGxX81zi_oKVrD8ndBAu0JfM4tL7KT4hjsPEsfslEmVudAVkjEsTJVHFTOMTfSMBcm9wXIiWPLNLH2Yt3iN-UMVmrY2i4LH0-ykab1npQGWy_RR4Od6Ya63Tu6ug3VDg6PkS_tRlJSUq4zzDNTEHkxH4PRQA
###
POST https://{{host}}/identity-api/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

client_id={{client_id}}
&scope={{scope}}
&client_secret={{client_secret}}
&grant_type={{grant_type}}

###
GET https://{{host}}/product-api/v1/product HTTP/1.1
Authorization: bearer {{token}}
Accept: */*